- name: 'Download and Install NGINX using Apt'
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true

- name: 'Start NGINX Service'
  service:
    name: nginx
    state: started

- name: 'Install nginx.conf to Remote Machine'
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config

- name: 'Reload NGINX'
  service:
    name: nginx
    state: reloaded
  when: nginx_config.changed
